### ISSUE TITLE
Webpack support

### ISSUE THREAD

**Issue by rbrtmrtn** [CityOfPhiladelphia/standards#20]
Hey @karissademi 👋 I'm working on a JavaScript app where I'd like to load Standards in using Webpack rather than over CDN. So I tried doing this:

    yarn add phila-standards

and then adding these lines to my JavaScript:

```
import 'phila-standards/dist/css/phila-standards.min.css';
import 'phila-standards/dist/js/phila-standards.min.js';
```

The CSS is working great, but for some reason the JavaScript doesn't seem to be running. (For example, the feedback button in the HTML boilerplate doesn't respond when you click it.)

I know this is pretty different from how Standards is used on `beta.phila.gov` and I'm happy to dig in and try to figure it out, but I thought I'd run it by you first in case you know of a better method.

Thanks!

**Comment by rbrtmrtn** [comment]
Actually, I changed the import to:

    import 'phila-standards';

and I think it's working now! I'll report back when I can test it a little more thoroughly :)

**Comment by karissademi** [comment]
That was going to be my suggestion! Let me know if there are any issues.

**Comment by timwis** [comment]
Also check out the v2 branch of parks-rec-app App.vue for how to import the standards app sass (note the include paths in webpack config)

**Comment by rbrtmrtn** [comment]
Thanks @timwis, I'll take a look!
