### ISSUE TITLE
Add style property to package.json

### ISSUE THREAD

**Issue by timwis** [CityOfPhiladelphia/standards#8]
Similar to `main`, `style` is a convention established for importing stylesheets (ie. in react). It's meant to point to the main entrypoint file.

So it'd be:
```
"style": "dist/css/phila-standards.css"
```

**Comment by karissademi** [comment]
Sure. It should point to the main uncompiled file, though, right? Like `main` does?

```
"style": "src/sass/phila-standards.scss"
```

**Comment by timwis** [comment]
Worth researching more, but my guess is no, because that would require preprocessing it to use it.

**Comment by karissademi** [comment]
Righto. Thanks.
