### ISSUE TITLE
Require deps like jQuery, postscribe

### ISSUE THREAD

**Issue by timwis** [CityOfPhiladelphia/standards#9]
The js files appear to make use of jQuery and postscribe, but don't import the modules. Instead they assume the modules are globally available (in the `window` via a `<script>` tag import). If someone's using this module via `require`, they're probably not importing jquery and the like with `<script>` tags though.

`package.json` should include both of these modules as `dependencies`, and the files that use the modules should import them via `require`, ie. `var $ = require('jquery')`

**Comment by karissademi** [comment]
True. Part of my reasoning for not including jQuery as a dependency was a note in on one of the [USDS Standards releases](https://github.com/18F/web-design-standards/releases/tag/v0.13.2) referring to the decision to remove jQuery from their dependencies, because they received feedback that it was conflicting with other versions of jQuery some sites were already using. If you think that probably doesn't make sense for us, I can certainly add it in.

Agreed that postscribe should be added as a dependency, that was an oversight.

**Comment by timwis** [comment]
Ah, i see.  That will come up when jQuery is global, like when you pull it in via a `<script>` tag, it gets attached to `window.$` and `window.jQuery`. But when you use it via CommonJS (`require('jquery')`) it _should_ only get attached to whatever variable you assigned it to, ie. a local `var $ = require('jquery')` and not pollute the global window space.

Although, tangentially, the main reason we need jQuery is for foundation's JS code, and foundation may require accessing it via the global window object. Not sure.

I think this falls into the "peer dependency" category of node modules, where you always `require` them when used in your code, but instead of putting them in `dependencies`, you put them in `peerDependencies`, and consumers install them separately.

Have you ever heard of foundation dropping jquery?

**Comment by karissademi** [comment]
I'll do some testing re: including jQuery with `require('jquery')` and see if that's an issue for foundation or not. Pretty sure Foundation won't be dropping jQuery any time soon.

**Comment by karissademi** [comment]
Looks like in order for this to work, we'll also need to add [jspm](http://jspm.io/). I'm not entirely prepared to go down that rabbit hole at the moment, especially as adding jQuery as a `<script>` tag provides more flexibility to the project owner. Thoughts?

**Comment by timwis** [comment]
What suggests jspm would be need to be involved?

**Comment by karissademi** [comment]
Hmm, upon closer inspection that does not appear to be the case. :D

**Comment by karissademi** [comment]
Fixed in bdba68785e5758268364261e8aa9fbd7915aa169.
